### ISSUE TITLE
The connected dataset seems expired

### ISSUE THREAD

**Issue by SoYuCry** [SharifAmit/Attention2Angio#2]
![image](https://user-images.githubusercontent.com/87529679/151584891-c3ea876a-4423-497f-b1e3-4482c68fe270.png)

**Comment by SharifAmit** [comment]
Hi,

You can download it from here.

Link : https://drive.google.com/file/d/1ARIZISmkBgVzSsg5yTksQ_-EIXjRv5hX/view?usp=sharing

Closing the issue.
